-- TokenFx central reporter server — initial schema (v0)
-- Hand-crafted to match apps/server/lib/db/schema.ts.
-- Idempotent: every CREATE uses IF NOT EXISTS; ALTER guarded with DO blocks.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS orgs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS teams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  team_id uuid REFERENCES teams(id) ON DELETE SET NULL,
  email text UNIQUE NOT NULL,
  sso_provider text NOT NULL,
  sso_subject text NOT NULL,
  role text NOT NULL DEFAULT 'member',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_role_check CHECK (role IN ('member', 'manager', 'admin'))
);

CREATE TABLE IF NOT EXISTS user_machines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  machine_id uuid NOT NULL,
  key_id text UNIQUE NOT NULL,
  secret_hash text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_seen_at timestamp with time zone,
  revoked_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS sessions_agg (
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id text NOT NULL,
  payload_hash text NOT NULL,
  started_at timestamp with time zone NOT NULL,
  ended_at timestamp with time zone NOT NULL,
  project_slug text NOT NULL,
  git_branch text,
  cc_version text,
  total_input_tokens bigint NOT NULL,
  total_output_tokens bigint NOT NULL,
  total_cache_read_tokens bigint NOT NULL,
  total_cache_creation_tokens bigint NOT NULL,
  total_cost_usd numeric(14, 6) NOT NULL,
  total_cost_usd_otel numeric(14, 6),
  turn_count integer NOT NULL,
  tool_call_count integer NOT NULL,
  avg_rating numeric(4, 3),
  cache_hit_ratio numeric(4, 3),
  output_input_ratio numeric(8, 4),
  subagent_usage_ratio numeric(4, 3),
  ingested_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, session_id)
);

CREATE INDEX IF NOT EXISTS idx_sessions_agg_started ON sessions_agg (started_at);
CREATE INDEX IF NOT EXISTS idx_sessions_agg_user_started ON sessions_agg (user_id, started_at);

CREATE TABLE IF NOT EXISTS model_breakdown_agg (
  user_id uuid NOT NULL,
  session_id text NOT NULL,
  model text NOT NULL,
  input_tokens bigint NOT NULL,
  output_tokens bigint NOT NULL,
  cache_read_tokens bigint NOT NULL,
  cache_creation_tokens bigint NOT NULL,
  cost_usd numeric(14, 6) NOT NULL,
  PRIMARY KEY (user_id, session_id, model)
);

CREATE TABLE IF NOT EXISTS tool_count_agg (
  user_id uuid NOT NULL,
  session_id text NOT NULL,
  tool_name text NOT NULL,
  count integer NOT NULL,
  PRIMARY KEY (user_id, session_id, tool_name)
);

CREATE TABLE IF NOT EXISTS cost_calibration_per_user (
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  family text NOT NULL,
  effective_rate numeric(6, 4) NOT NULL,
  sample_session_count integer NOT NULL,
  sum_otel_cost numeric(14, 6) NOT NULL,
  sum_local_cost numeric(14, 6) NOT NULL,
  last_updated_at timestamp with time zone NOT NULL,
  PRIMARY KEY (user_id, family)
);

CREATE TABLE IF NOT EXISTS ingestion_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid,
  machine_id uuid NOT NULL,
  key_id text NOT NULL,
  payload_size_bytes integer NOT NULL,
  accepted_count integer NOT NULL,
  skipped_count integer NOT NULL,
  rejected_count integer NOT NULL,
  request_ip text,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  errors_json jsonb
);

CREATE INDEX IF NOT EXISTS idx_ingestion_log_received ON ingestion_log (received_at);
CREATE INDEX IF NOT EXISTS idx_ingestion_log_user ON ingestion_log (user_id, received_at);

-- Compound FKs (Drizzle's compound-FK syntax is awkward — apply via raw SQL).
-- Both reference sessions_agg(user_id, session_id) so a session deletion cascades
-- to its per-model and per-tool breakdowns.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_mba_session'
  ) THEN
    ALTER TABLE model_breakdown_agg
      ADD CONSTRAINT fk_mba_session
      FOREIGN KEY (user_id, session_id)
      REFERENCES sessions_agg(user_id, session_id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_tca_session'
  ) THEN
    ALTER TABLE tool_count_agg
      ADD CONSTRAINT fk_tca_session
      FOREIGN KEY (user_id, session_id)
      REFERENCES sessions_agg(user_id, session_id)
      ON DELETE CASCADE;
  END IF;
END $$;
