import fs from 'node:fs';
import path from 'node:path';
import { z } from 'zod';

/**
 * Reporter configuration locked in spec REQ-7.
 *
 * Lives at `data/reporter-config.json` (file mode 0600). The provisioning
 * flow that *acquires* `key_id` + `secret` is owned by the carved-out spec
 * `central-server-onboarding.md`; for v0 of THIS spec the file is hand-written
 * (or generated by `scripts/reporter-config-init.ts`).
 *
 * The shape is asserted with Zod so an old/handwritten file with a missing
 * field fails fast with a clear error message rather than producing a runtime
 * undefined-secret crash inside the signer.
 */

const ReporterConfigSchema = z
  .object({
    key_id: z.string().min(1),
    secret: z.string().min(1),
    machine_id: z.string().min(1),
    user_email: z.string().email(),
    central_url: z.string().url(),
    project_secret: z.string().min(1),
  })
  .strict();

export type ReporterConfig = z.infer<typeof ReporterConfigSchema>;

const DEFAULT_CONFIG_PATH = (): string =>
  path.join(process.cwd(), 'data', 'reporter-config.json');

/**
 * Read and validate the reporter config.
 *
 * @returns the parsed config, or `null` if the file does not exist (the
 *   "not configured" gate from REQ-11). All other failure modes — bad JSON,
 *   missing fields, wrong types — throw with a descriptive `Error`, because
 *   they signal a manual setup mistake the user MUST see.
 */
export const readConfig = (filePath?: string): ReporterConfig | null => {
  const resolved = filePath ?? DEFAULT_CONFIG_PATH();
  if (!fs.existsSync(resolved)) {
    return null;
  }
  let raw: string;
  try {
    raw = fs.readFileSync(resolved, 'utf8');
  } catch (err) {
    throw new Error(`reporter-config read failed: ${(err as Error).message}`);
  }
  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch (err) {
    throw new Error(
      `reporter-config invalid JSON at ${resolved}: ${(err as Error).message}`,
    );
  }
  const parsed = ReporterConfigSchema.safeParse(json);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((i) => `${i.path.join('.') || '<root>'}: ${i.message}`)
      .join('; ');
    throw new Error(
      `reporter-config schema mismatch at ${resolved}: ${issues}`,
    );
  }
  return parsed.data;
};

/**
 * Default location used by `runReporter()` and CLI scripts. Exported so
 * callers can construct platform-specific paths without re-deriving the
 * convention.
 */
export const defaultConfigPath = DEFAULT_CONFIG_PATH;
